spring:
  datasource:
    password:
    url: jdbc:mysql://127.0.0.1:3306/gbe?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true